name: reusable Workflow
on: 
    workflow_call:
        inputs:
            artifact-name:
                default: dist
                description: Taking the artifact name
                type: string
                required: false
        outputs:
            result:
                description: Value of result output
                value: ${{ jobs.deploy.outputs.outcome}}
jobs:
    deploy:
        outputs:
            outcome: ${{ steps.set-result.outputs.step-result}}
        runs-on: ubuntu-latest
        steps:
            - name: Downloading artifact
              uses: actions/download-artifact@v4
              with:
                name: ${{inputs.artifact-name}}
            - name: List of files
              run: ls
            - name: output information
              run: echo "Reusable Workflow"
            - name: set result output
              id: set-result
              run: echo "step-result=success" >> $GITHUB_OUTPUT
